voice_model:
  model_path: "/Users/amarchheda/Desktop/projects/InterviewWarmupLocal/voice_models/vosk-model-en-us-0.42-gigaspeech"
  channels: 1
  sample_rate: 16000
  model_type: whisper
llm:
  summary_model: "Qwen/Qwen2-0.5B-Instruct-GGUF"
  review_model: "Qwen/Qwen2-1.5B-Instruct-GGUF"
  request_timeout: 320.0
  chunk_size: 512
  chunk_overlap: 75
  embed_model: "BAAI/bge-small-en-v1.5"
  prompt_template:
    overall_analysis: |
      Based on the following individual question-answer analyses:
      {analyses}

      Resume:
      {resume}

      Job Description:
      {job_description}

      Provide an overall evaluation of the candidate's interview performance, ensuring that you consider the quality and depth of the answers, not just the presence of keywords.

      Use the following criteria, with scores from 1 to 5 (1 = Poor, 5 = Excellent):
      1. Relevance and coherence across all answers.
      2. Alignment with the job description.
      3. Effective use of experience from the resume.
      4. Depth of information provided across answers.
      5. Consistency of performance across questions.

      Please provide your overall evaluation in this structured format:

      **Overall Scoring Matrix**:
      - Relevance & Coherence: [Score]
      - Alignment: [Score]
      - Use of Experience: [Score]
      - Depth of Information: [Score]
      - Consistency: [Score]

      **Overall Summary**:
      - Were the answers generally meaningful and well thought out? (Yes/No)
      - Key strengths across the interview:
      - Areas for improvement across the interview:
      - Final assessment of candidate fit for the role:


    question_analysis: |
      You are an AI assistant tasked with evaluating a candidate's interview answer using a scoring matrix based on the job description and resume.

      Job Description:
      {job_description}

      Question:
      {question}

      Candidate’s Answer:
      {answer}

      Evaluate the candidate's answer based on its content, context, and relevance to the Question. Consider whether the answer provides meaningful and useful information. If the answer does not provide enough useful information, state that clearly.

      Use the following criteria, with scores from 1 to 5 (1 = Poor, 5 = Excellent):
      1. Relevance of the answer to the question and job description.
      2. Clarity and coherence of the answer.
      3. Alignment with the job description requirements.
      5. Depth and usefulness of the information provided.

      Please provide your evaluation in this structured format:

      **Scoring Matrix**:
      - Relevance: [Score]
      - Clarity: [Score]
      - Alignment: [Score]
      - Use of Experience: [Score]
      - Depth of Information: [Score]

      **Detailed Feedback**:
      - Does the answer provide enough useful information? (Yes/No)
      - Key strengths (if applicable):
      - Areas for improvement:
      - Overall assessment of this answer:
    
    resume_summary: |
      You are an expert at summarizing resumes and extracting key information.
      
      Given the following resume:
      {resume}

      please provide a summary of the resume based on the following criteria:
      - Key skills and experiences
      - Achievements and accomplishments
      - Areas of expertise
      - Education and qualifications
      - Work experience
      - Projects and contributions
      - Certifications and awards
      - Areas of expertise
      
      Keep the summary concise and to the point, ensuring that it captures the most important information.

    job_description_summary: |
      You are an expert at summarizing job descriptions and extracting key information.

      Given the following job description:
      {job_description}

      please provide a summary of the job description based on the following criteria:
      - Key skills and experiences
      - Achievements and accomplishments
      - Areas of expertise
      - Education and qualifications
      - Work experience
      - Projects and contributions
      - Certifications and awards
      - Areas of expertise

      Keep the summary concise and to the point, ensuring that it captures the most important information.
